### ISSUE TITLE
Fixed Error and Bugs (Common Mistakes) eng ver (Don't close Issues Tomato)

### ISSUE THREAD

**Issue by Almazmsi** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#100]
### 1. Missing Intent
![unknown](https://user-images.githubusercontent.com/72695998/154854554-cd2a2153-9ac3-404a-80f6-089961568458.png)
![opera_UEYtDE9mtP](https://user-images.githubusercontent.com/72695998/154824780-f60958bd-859e-4163-baeb-d6df81b56719.png)

### 2. Lavalink not work (use server 02 and 03, but i don't know 01 server)

ㅤㅤ**02 server**
![Code_-_Insiders_To1xbiJfq9](https://user-images.githubusercontent.com/72695998/154824816-16789f10-43ac-4ee5-843e-41b1980af369.png)
ㅤㅤ**03 server**
![Code_-_Insiders_DyhJZx9X57](https://user-images.githubusercontent.com/72695998/154824822-3aa08caa-25db-4d19-9984-5d90ef711a34.png)

### 3. Missing Acces to use owner cmd

ㅤㅤ**copy**
![DiscordPTB_jNcZazBXhD](https://user-images.githubusercontent.com/72695998/154824867-a322c459-4c5a-4db0-82b1-0a2b83cd43f5.png)
ㅤㅤ**paste**
![Code_-_Insiders_kJXZf6a3fu](https://user-images.githubusercontent.com/72695998/154824877-b1c104df-5b68-4955-9621-e36218650e07.png)

### 4. Not work Spotify

ㅤㅤ**4.1 Go to https://developer.spotify.com/dashboard/ and Login**
![7CipoQqjy2](https://user-images.githubusercontent.com/72695998/154824967-f3fec104-d84c-42a4-ba61-c62b6e859f36.png)
ㅤㅤ**4.2  Accept terms**
![vwn85vIx20](https://user-images.githubusercontent.com/72695998/154825537-101dd0aa-fa19-4410-93c1-90ae3b87fe9a.png)
ㅤㅤ**4.3 Create new app**
![opera_X2ydndP6oK](https://user-images.githubusercontent.com/72695998/154825546-1b364316-8c24-4a0d-85d1-b581fb561ce9.png)
ㅤㅤ**4.4 Name app**
![opera_OfY6qNK7Lx](https://user-images.githubusercontent.com/72695998/154825550-f342cc81-2b0e-4632-b54e-a5f035a51a3c.png)
ㅤㅤ**4.5 Click Cliend Secret ID**
![opera_DJVfak6bf4](https://user-images.githubusercontent.com/72695998/154825644-caf12b52-657e-458d-8d94-f8813b7eb12e.png)
ㅤㅤ**4.6 Paste config.json**
![Code_-_Insiders_NzbW9QyM6X](https://user-images.githubusercontent.com/72695998/154825660-fd9888a3-1c11-48c5-b96f-1ea893415e5f.png)

### 5. Slash Command
ㅤㅤ**1. {prefix}deployslash**
![opera_NTAW4insKT](https://user-images.githubusercontent.com/72695998/154826441-d20ba40e-b992-4f23-9b73-a268458134d8.png)
ㅤㅤ**2. invite again**
https://discord.com/api/oauth2/authorize?client_id=${user.id}&permissions=8&scope=bot%20applications.commands ( ${user.id} - id bot)
![opera_3oBSwepmCz](https://user-images.githubusercontent.com/72695998/154826542-6a7a2cb7-c26f-44a0-8c8d-7996f02e0d5d.png)

### 6. Error queue command
`=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setAuthor (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/structures/MessageEmbed.js:392:32)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queue.js:45:12)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===`
_**Fix**_
ㅤㅤ**1. add k**
![Code_-_Insiders_U6wr2njs7s](https://user-images.githubusercontent.com/72695998/154825999-173f7497-ee79-4a66-870e-3eb1ead21670.png)
ㅤㅤ**2. add //**
![Code_-_Insiders_dIy2vSZMMa](https://user-images.githubusercontent.com/72695998/154826009-9f858289-6e62-454d-85a5-26ca8cdba046.png)
ㅤㅤ**3. reload cmd and enjoy**
![DiscordPTB_ILmZeMJdat](https://user-images.githubusercontent.com/72695998/154826022-6ef057ca-3f64-46fd-9283-f9e59584630a.png)

### 7. Error NP
`=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setAuthor (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/structures/MessageEmbed.js:392:32)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/nowplaying.js:31:8)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===`
_**Fix**_
ㅤㅤ**1. add // 31-33**
![Code_-_Insiders_bl90NI1bWF](https://user-images.githubusercontent.com/72695998/154826099-1a0815ee-b508-402e-a412-9d30ac3a54e9.png)
ㅤㅤ**2. reload cmd and enjoy**
![DiscordPTB_ZTEhBrEJd5](https://user-images.githubusercontent.com/72695998/154826196-a05c4b0a-0f42-496d-8a62-5c9561f2e43d.png)

### 8. Error queuestatus
`
=== UNHANDLED REJECTION ===
Reason:  ReferenceError: createBar is not defined
    at eval (eval at run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queuestatus.js:38:90), <anonymous>:1:40)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queuestatus.js:38:90)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===
`
_**Fix**_
ㅤㅤ**1. add // 38**
![Code_-_Insiders_m8wc8IXVDT](https://user-images.githubusercontent.com/72695998/154826697-8ba791dd-7959-4d23-83a9-0fcd34932b3d.png)
ㅤㅤ**2. reload cmd and enjoy**
![DiscordPTB_YmBJYpzsXx](https://user-images.githubusercontent.com/72695998/154826708-9b93a6bf-d458-4798-b72b-c58ba9f86c0d.png)

ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ**I will update this post as I find problems. Thanks**

**Comment by Kurumii-ii** [comment]
What about radio command

**Comment by Almazmsi** [comment]
> What about radio command

I`m not fixed. Wait

**Comment by Almazmsi** [comment]
### 9. Error Language
`=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (C:\Users\banlo\Desktop\Quraso Music\node_modules\discord.js\src\util\Util.js:416:41)
    at MessageEmbed.setAuthor (C:\Users\banlo\Desktop\Quraso Music\node_modules\discord.js\src\structures\MessageEmbed.js:392:32)
    at first_layer (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\language.js:77:10)
    at Object.run (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\language.js:37:5)
    at module.exports (C:\Users\banlo\Desktop\Quraso Music\events\guild\messageCreate.js:309:17)
=== UNHANDLED REJECTION ===`
_**Fix**_
ㅤㅤ**1. add // 77**
![Code_-_Insiders_pPvQkOvOAl](https://user-images.githubusercontent.com/72695998/154852410-edc7d916-cf20-4dda-843a-0926633daceb.png)
ㅤㅤ**2. reload cmd and enjoy**
![Code_-_Insiders_yijGNRD5eP](https://user-images.githubusercontent.com/72695998/154852415-38001fe4-77da-448f-ba32-068a188b9426.png)

**Comment by Almazmsi** [comment]
### 10. Error reset
`ReferenceError: config is not defined
    at eval (eval at <anonymous> (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33), <anonymous>:1:27)
    at C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: config is not defined
    at eval (eval at <anonymous> (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33), <anonymous>:1:27)
    at C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: config is not defined
    at eval (eval at <anonymous> (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33), <anonymous>:1:27)
    at C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
**_Fix_**
ㅤ**1. add // 66**
![Code_-_Insiders_AScZD6vpFs](https://user-images.githubusercontent.com/72695998/154853793-01c3e9f8-bc43-4c8c-a745-840ab53a0b99.png)
ㅤㅤ**2. reload cmd and enjoy (P.S: I'm change cmdreload.js and add aliases "cmdr")**
![DiscordPTB_5SOpOY5kLA](https://user-images.githubusercontent.com/72695998/154853813-966d786b-ce96-4e5d-ac79-ab4be3a4da6d.png)

**Comment by MondoPIX** [comment]
here's another one

```
ReferenceError: button_support_dc is not defined
at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🔰 Info/invite.js:30:87)
at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)

 === UNHANDLED REJECTION ===
Reason:  ReferenceError: button_support_dc is not defined
     at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🔰 Info/invite.js:30:87)
     at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
 === UNHANDLED REJECTION ===
```
![image](https://user-images.githubusercontent.com/22109196/154859459-0b4c7dbd-6ea3-4713-bfd4-533db170b860.png)
![image](https://user-images.githubusercontent.com/22109196/154859482-58b5710c-471d-47e4-adc6-8fe371371a94.png)

**Comment by Almazmsi** [comment]
> here's another one
> 
> ```
> ReferenceError: button_support_dc is not defined
> at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🔰 Info/invite.js:30:87)
> at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
> 
>  === UNHANDLED REJECTION ===
> Reason:  ReferenceError: button_support_dc is not defined
>      at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🔰 Info/invite.js:30:87)
>      at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
>  === UNHANDLED REJECTION ===
> ```
> 
> ![image](https://user-images.githubusercontent.com/22109196/154859459-0b4c7dbd-6ea3-4713-bfd4-533db170b860.png) ![image](https://user-images.githubusercontent.com/22109196/154859482-58b5710c-471d-47e4-adc6-8fe371371a94.png)

Wait 1 hour)

**Comment by MondoPIX** [comment]
@Almazmsi  I already did

**Comment by Almazmsi** [comment]
![image](https://user-images.githubusercontent.com/72695998/154859981-e8eedbd6-579c-480e-bcf5-89bce4949c86.png)
@MondoPIX  Hmm

**Comment by MondoPIX** [comment]
try ;;invite

**Comment by Almazmsi** [comment]
> try ;;invite

wait :D

**Comment by Almazmsi** [comment]
![image](https://user-images.githubusercontent.com/72695998/154860076-3e0c110f-1aa0-40c7-9850-9acdd6248707.png)
Not edit code)
![image](https://user-images.githubusercontent.com/72695998/154860119-99455710-e876-4c49-99f4-3c317c6aabbc.png)

**Comment by MondoPIX** [comment]
he did it only to me
![image](https://user-images.githubusercontent.com/22109196/154860131-c0bb7f77-24c5-4822-9384-d451f349ec38.png)

**Comment by Almazmsi** [comment]
> he did it only to me ![image](https://user-images.githubusercontent.com/22109196/154860131-c0bb7f77-24c5-4822-9384-d451f349ec38.png)

number buttons?

**Comment by Almazmsi** [comment]
![image](https://user-images.githubusercontent.com/72695998/154860234-e91bf257-545e-4835-a750-d698aed1278f.png)
Fixed

**Comment by MondoPIX** [comment]
button_support_dc on 30

**Comment by Almazmsi** [comment]
> button_support_dc on 30

delete 27 line and button_suppord_discord

**Comment by Almazmsi** [comment]
```const {
  MessageEmbed,
  MessageButton,
  MessageActionRow
} = require("discord.js")
const config = require(`${process.cwd()}/botconfig/config.json`);
var ee = require(`${process.cwd()}/botconfig/embed.json`);
const emoji = require(`${process.cwd()}/botconfig/emojis.json`);
const {
  handlemsg
} = require(`${process.cwd()}/handlers/functions`)
module.exports = {
  name: "invite",
  category: "🔰 Info",
  aliases: ["add"],
  usage: "invite",
  description: "Gives you an Invite link for this Bot",
  type: "bot",
  run: async (client, message, args, cmduser, text, prefix, player, es, ls) => {
    let user = message.mentions.users.first() || client.user;
    if (user) {
      if (!user.bot) return interaction.reply({
        ephemeral: true,
        content: "<:no:833101993668771842> You can't Invite a Normal user! **IT MUST BE A BOT**"
      })
      let button_public_invite = new MessageButton().setStyle('LINK').setLabel(handlemsg(client.la[ls].cmds.info.invite.buttons.public)).setURL("https://discord.com/api/oauth2/authorize?client_id=734513783338434591&permissions=8&scope=bot%20applications.commands")
      let button_invite = new MessageButton().setStyle('LINK').setLabel("Invite " + user.username).setURL(`https://discord.com/api/oauth2/authorize?client_id=${user.id}&permissions=8&scope=bot%20applications.commands`)
      //array of all buttons
      const allbuttons = [new MessageActionRow().addComponents([button_public_invite, button_invite])]
      message.reply({
        embeds: [new MessageEmbed()
          .setColor(ee.color)
          .setTitle(`Invite: __**${user.tag}**__`)
          .setDescription(`||[*Click here for an Invitelink without Slash Commands*](https://discord.com/api/oauth2/authorize?client_id=${user.id}&permissions=8&scope=bot)||`)
          .setURL(`https://discord.com/api/oauth2/authorize?client_id=${user.id}&permissions=8&scope=bot%20applications.commands`)
          .setFooter(client.getFooter(`${user.username} | powered by milrato.dev`, "https://imgur.com/jPItIw0.gif"))
        ],
        components: allbuttons
      });
    }
  }
}```

**Comment by MondoPIX** [comment]
I just commented the string (27) with //

**Comment by Almazmsi** [comment]
> I just commented the string with //

 no not commented. Delete

**Comment by Almazmsi** [comment]
![image](https://user-images.githubusercontent.com/72695998/154865972-85821d7a-bd7d-4488-b60f-b3ba8ca0a333.png)
Bug when installing on hosting ubuntu. But when it's on PC everything is fine.

Need time fix

**Comment by MondoPIX** [comment]
I use the bot on ubuntu and I did not find this error

**Comment by Almazmsi** [comment]
> I use the bot on ubuntu and I did not find this error

Ur version node? and give ur node_modules

**Comment by MondoPIX** [comment]
> > I use the bot on ubuntu and I did not find this error
> 
> Ur version node? and give ur node_modules

17.2.0

**Comment by MondoPIX** [comment]
```
botdiscord@pix-server2:~/discord-js-lavalink-Music-Bot-erela-js/node_modules$ ls -l
total 560
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 abbrev
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 agent-base
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 ansi-regex
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 aproba
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 are-we-there-yet
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 asynckit
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 axios
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 balanced-match
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 base64-js
drwxrwxr-x 6 botdiscord botdiscord  4096 Jan 22 12:17 better-sqlite3
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 bindings
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 bl
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 boolbase
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 brace-expansion
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 buffer
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 cheerio
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 cheerio-select
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 chownr
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 code-point-at
drwxrwxr-x 5 botdiscord botdiscord  4096 Jan 22 12:17 colors
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 color-support
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 combined-stream
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 concat-map
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 console-control-strings
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 core-util-is
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 cpu-stat
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 css-select
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 css-what
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 debug
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 decompress-response
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 deep-extend
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 delayed-stream
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 delegates
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 detect-libc
drwxrwxr-x 8 botdiscord botdiscord  4096 Jan 22 12:17 discord-api-types
drwxrwxr-x 7 botdiscord botdiscord  4096 Jan 22 12:28 @discordjs
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 discord.js
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 domelementtype
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 domhandler
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 dom-serializer
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 domutils
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 emoji-regex
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 end-of-stream
drwxrwxr-x 6 botdiscord botdiscord  4096 Jan 22 12:17 enmap
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 entities
drwxrwxr-x 5 botdiscord botdiscord  4096 Jan 22 12:17 erela.js
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 erela.js-apple
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 erela.js-deezer
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 erela.js-facebook
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 erela.js-spotify
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 expand-template
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 file-uri-to-path
drwxrwxr-x 2 botdiscord botdiscord  4096 Feb 15 16:41 follow-redirects
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 form-data
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 fs-constants
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 fs-minipass
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 fs.realpath
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 gauge
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 github-from-package
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 glob
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 has-unicode
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 htmlparser2
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 https-proxy-agent
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 ieee754
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 inflight
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 inherits
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 ini
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 isarray
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 is-fullwidth-code-point
drwxrwxr-x 3 botdiscord botdiscord 20480 Jan 22 12:17 lodash
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 lru-cache
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 make-dir
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 mime-db
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 mime-types
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 mimic-response
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 minimatch
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 minimist
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 minipass
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 minizlib
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 mkdirp
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 mkdirp-classic
drwxrwxr-x 7 botdiscord botdiscord  4096 Jan 22 12:17 moment
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 ms
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 napi-build-utils
drwxrwxr-x 6 botdiscord botdiscord  4096 Jan 22 12:17 node-abi
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 node-addon-api
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 node-fetch
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 nopt
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 npmlog
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 nth-check
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 number-is-nan
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 object-assign
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 once
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 on-change
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 parse5
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 parse5-htmlparser2-tree-adapter
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 path-is-absolute
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 petitio
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 prebuild-install
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 process-nextick-args
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 pump
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 radio-browser
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 randombytes
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 rc
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 readable-stream
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 rimraf
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 safe-buffer
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:28 @sapphire
drwxrwxr-x 7 botdiscord botdiscord  4096 Jan 22 12:17 semver
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 serialize-javascript
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 set-blocking
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 signal-exit
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 simple-concat
drwxrwxr-x 3 botdiscord botdiscord  4096 Feb 15 16:41 simple-get
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 @sindresorhus
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 string_decoder
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 string-width
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 strip-ansi
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 strip-json-comments
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 tar
drwxrwxr-x 4 botdiscord botdiscord  4096 Jan 22 12:17 tar-fs
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 tar-stream
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 tiny-typed-emitter
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 tr46
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 tslib
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 ts-mixer
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 tunnel-agent
drwxrwxr-x 5 botdiscord botdiscord  4096 Jan 22 12:28 @types
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 util-deprecate
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 webidl-conversions
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 whatwg-url
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 wide-align
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 wrappy
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 ws
drwxrwxr-x 2 botdiscord botdiscord  4096 Jan 22 12:17 yallist
drwxrwxr-x 3 botdiscord botdiscord  4096 Jan 22 12:17 zod

```

**Comment by Almazmsi** [comment]
i'm fixed :D

**Comment by Almazmsi** [comment]
***k radio. I'm stupid maybe?

**Comment by Almazmsi** [comment]
### 11 Error playprevious
`0|Test  | === UNHANDLED REJECTION ===
0|Test  | Reason:  ReferenceError: layer is not defined
0|Test  |     at Object.run (/root/bots/qurasomusic/commands/🎶 Music/playprevious.js:57:31)
0|Test  |     at module.exports (/root/bots/qurasomusic/events/guild/messageCreate.js:309:17)
0|Test  | === UNHANDLED REJECTION ===`
![image](https://user-images.githubusercontent.com/72695998/154972868-9c74cdc2-bd3a-4123-9f0a-06f0b9767164.png)
**_FIX_**
ㅤㅤ**1. add p (layer).**
![image](https://user-images.githubusercontent.com/72695998/154973331-e93cfcd1-849a-4b46-b46a-6a3db8002d2f.png)
ㅤㅤ**2. reload cmd and enjoy.**
![image](https://user-images.githubusercontent.com/72695998/154973477-c877aac0-0f09-4744-9874-030e31639aef.png)

**Comment by MondoPIX** [comment]
@Almazmsi I don't know if you noticed this but when you put the volume at 100% it feels like it is at 200%
![image](https://user-images.githubusercontent.com/22109196/155028295-530f5063-966d-4049-9573-738dd90e628f.png)
![volume](https://user-images.githubusercontent.com/22109196/155029749-5ecc243b-0c85-465b-90f7-b936cbd6f38e.png)

https://www.youtube.com/watch?v=bfYd2kckimg

**Comment by Almazmsi** [comment]
> @Almazmsi I don't know if you noticed this but when you put the volume at 100% it feels like it is at 200% ![image](https://user-images.githubusercontent.com/22109196/155028295-530f5063-966d-4049-9573-738dd90e628f.png) ![volume](https://user-images.githubusercontent.com/22109196/155029749-5ecc243b-0c85-465b-90f7-b936cbd6f38e.png)
> 
> https://www.youtube.com/watch?v=bfYd2kckimg

{prefix}volume check
volume 30% ideal

**Comment by Almazmsi** [comment]
I'll post a searchradio fix later)
 My friend helped me, but radio not fixed unu
