### ISSUE TITLE
Фиксы багов и ошибок (Распространенные ошибки) rus ver (Don't close Issues Tomato)

### ISSUE THREAD

**Issue by Almazmsi** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#101]
Привет. Я знаю что есть люди которые пользуются этим ботов в СНГ странах, так вот. Из-за того что кодер написал коряво бота мне пришлось малёха так сказать помочь вам чтобы бот работал стабильно и без ошибок. Позже будет форк этого бота на русском языке

### 1. Нет интентов. 
![unknown](https://user-images.githubusercontent.com/72695998/154854581-2cbee0eb-36d7-4196-97fd-385808f0f8a8.png)
![opera_UEYtDE9mtP](https://user-images.githubusercontent.com/72695998/154824780-f60958bd-859e-4163-baeb-d6df81b56719.png)

### 2. Lavalink не работает (используйте 02 или 03, я не знаю есть ли  01 сервер)

ㅤㅤ**02 сервер**
![Code_-_Insiders_To1xbiJfq9](https://user-images.githubusercontent.com/72695998/154824816-16789f10-43ac-4ee5-843e-41b1980af369.png)
ㅤㅤ**03 сервер**
![Code_-_Insiders_DyhJZx9X57](https://user-images.githubusercontent.com/72695998/154824822-3aa08caa-25db-4d19-9984-5d90ef711a34.png)

### 3. Недостаточно прав для использование команд владельца
ㅤㅤ**копируем**
![DiscordPTB_jNcZazBXhD](https://user-images.githubusercontent.com/72695998/154824867-a322c459-4c5a-4db0-82b1-0a2b83cd43f5.png)
ㅤㅤ**вставляем**
![Code_-_Insiders_kJXZf6a3fu](https://user-images.githubusercontent.com/72695998/154824877-b1c104df-5b68-4955-9621-e36218650e07.png)

### 4. Не работает Spotify, или иными словами: Бот не ищет музык со спотифая

ㅤㅤ**4.1 Идем на сайт https://developer.spotify.com/dashboard/ и логинимся**
![7CipoQqjy2](https://user-images.githubusercontent.com/72695998/154824967-f3fec104-d84c-42a4-ba61-c62b6e859f36.png)
ㅤㅤ**4.2  Принимаем правила**
![vwn85vIx20](https://user-images.githubusercontent.com/72695998/154825537-101dd0aa-fa19-4410-93c1-90ae3b87fe9a.png)
ㅤㅤ**4.3 Создаем приложение**
![opera_X2ydndP6oK](https://user-images.githubusercontent.com/72695998/154825546-1b364316-8c24-4a0d-85d1-b581fb561ce9.png)
ㅤㅤ**4.4 Придумываем имя ему**
![opera_OfY6qNK7Lx](https://user-images.githubusercontent.com/72695998/154825550-f342cc81-2b0e-4632-b54e-a5f035a51a3c.png)
ㅤㅤ**4.5 Нажимаем на Cliend Secret ID**
![opera_DJVfak6bf4](https://user-images.githubusercontent.com/72695998/154825644-caf12b52-657e-458d-8d94-f8813b7eb12e.png)
ㅤㅤ**4.6 Вставляем в config.json**
![Code_-_Insiders_NzbW9QyM6X](https://user-images.githubusercontent.com/72695998/154825660-fd9888a3-1c11-48c5-b96f-1ea893415e5f.png)

### 5. Слеш команды (или в простонародии Слеши) 
ㅤㅤ**1. {prefix}deployslash**
![opera_NTAW4insKT](https://user-images.githubusercontent.com/72695998/154826441-d20ba40e-b992-4f23-9b73-a268458134d8.png)
ㅤㅤ**2. И по новой приглашаем**
https://discord.com/api/oauth2/authorize?client_id=${user.id}&permissions=8&scope=bot%20applications.commands ( ${user.id} -айди бота)
![opera_3oBSwepmCz](https://user-images.githubusercontent.com/72695998/154826542-6a7a2cb7-c26f-44a0-8c8d-7996f02e0d5d.png)

### 6. Ошибка queue команды
`=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setAuthor (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/structures/MessageEmbed.js:392:32)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queue.js:45:12)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===`
_**Исправлено**_
ㅤㅤ**1. Добавить буковку k**
![Code_-_Insiders_U6wr2njs7s](https://user-images.githubusercontent.com/72695998/154825999-173f7497-ee79-4a66-870e-3eb1ead21670.png)
ㅤㅤ**2. Закомментировать фрагмент текста //**
![Code_-_Insiders_dIy2vSZMMa](https://user-images.githubusercontent.com/72695998/154826009-9f858289-6e62-454d-85a5-26ca8cdba046.png)
ㅤㅤ**3. Перезагружаем команды и наслаждаемся**
![DiscordPTB_ILmZeMJdat](https://user-images.githubusercontent.com/72695998/154826022-6ef057ca-3f64-46fd-9283-f9e59584630a.png)

### 7. Ошика NP
`=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setAuthor (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/structures/MessageEmbed.js:392:32)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/nowplaying.js:31:8)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===`
_**Исправлено**_
ㅤㅤ**1. Комментируем // 31-33**
![Code_-_Insiders_bl90NI1bWF](https://user-images.githubusercontent.com/72695998/154826099-1a0815ee-b508-402e-a412-9d30ac3a54e9.png)
ㅤㅤ**2. Перезагружаем команды и наслаждаемся**
![DiscordPTB_ZTEhBrEJd5](https://user-images.githubusercontent.com/72695998/154826196-a05c4b0a-0f42-496d-8a62-5c9561f2e43d.png)

### 8. Ошибка queuestatus
`
=== UNHANDLED REJECTION ===
Reason:  ReferenceError: createBar is not defined
    at eval (eval at run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queuestatus.js:38:90), <anonymous>:1:40)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queuestatus.js:38:90)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===
`
_**Исправлено**_
ㅤㅤ**1. Комментируем // 38**
![Code_-_Insiders_m8wc8IXVDT](https://user-images.githubusercontent.com/72695998/154826697-8ba791dd-7959-4d23-83a9-0fcd34932b3d.png)
ㅤㅤ**2. Перезагружаем команды и наслаждаемся**
![DiscordPTB_YmBJYpzsXx](https://user-images.githubusercontent.com/72695998/154826708-9b93a6bf-d458-4798-b72b-c58ba9f86c0d.png)

ㅤㅤㅤㅤㅤㅤㅤㅤㅤ**По мере проблем и нахождения новых багов-ошибок буду дополнять этот пост . Спасибо**

**Comment by Almazmsi** [comment]
### 9. Ошибка выбора языка
`=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (C:\Users\banlo\Desktop\Quraso Music\node_modules\discord.js\src\util\Util.js:416:41)
    at MessageEmbed.setAuthor (C:\Users\banlo\Desktop\Quraso Music\node_modules\discord.js\src\structures\MessageEmbed.js:392:32)
    at first_layer (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\language.js:77:10)
    at Object.run (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\language.js:37:5)
    at module.exports (C:\Users\banlo\Desktop\Quraso Music\events\guild\messageCreate.js:309:17)
=== UNHANDLED REJECTION ===`
_**Исправлено**_
ㅤㅤ**1. Закомментируем строку // 77**
![Code_-_Insiders_pPvQkOvOAl](https://user-images.githubusercontent.com/72695998/154852410-edc7d916-cf20-4dda-843a-0926633daceb.png)
ㅤㅤ**2. Перезагружаем команды и наслаждаемся**
![Code_-_Insiders_yijGNRD5eP](https://user-images.githubusercontent.com/72695998/154852415-38001fe4-77da-448f-ba32-068a188b9426.png)

**Comment by Almazmsi** [comment]
### 10. Ошибка команды reset
`ReferenceError: config is not defined
    at eval (eval at <anonymous> (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33), <anonymous>:1:27)
    at C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: config is not defined
    at eval (eval at <anonymous> (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33), <anonymous>:1:27)
    at C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: config is not defined
    at eval (eval at <anonymous> (C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33), <anonymous>:1:27)
    at C:\Users\banlo\Desktop\Quraso Music\commands\⚙️ Settings\reset.js:66:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
**_Исправлено_**
ㅤ**1. Комментируем строку // 66**
![Code_-_Insiders_AScZD6vpFs](https://user-images.githubusercontent.com/72695998/154853793-01c3e9f8-bc43-4c8c-a745-840ab53a0b99.png)
ㅤㅤ**2. Перезагружаем команды и наслаждаемся (P.S: Я сменил cmdreload.js и добавил алиас "cmdr")**
![DiscordPTB_5SOpOY5kLA](https://user-images.githubusercontent.com/72695998/154853813-966d786b-ce96-4e5d-ac79-ab4be3a4da6d.png)

**Comment by Almazmsi** [comment]
### 11 Error playprevious
`0|Test  | === UNHANDLED REJECTION ===
0|Test  | Reason:  ReferenceError: layer is not defined
0|Test  |     at Object.run (/root/bots/qurasomusic/commands/🎶 Music/playprevious.js:57:31)
0|Test  |     at module.exports (/root/bots/qurasomusic/events/guild/messageCreate.js:309:17)
0|Test  | === UNHANDLED REJECTION ===`
![image](https://user-images.githubusercontent.com/72695998/154972868-9c74cdc2-bd3a-4123-9f0a-06f0b9767164.png)
**_Исправлено_**
ㅤㅤ**1. Добавляем p (layer).**
![image](https://user-images.githubusercontent.com/72695998/154973331-e93cfcd1-849a-4b46-b46a-6a3db8002d2f.png)
ㅤㅤ**2. Перезагружаем команды и наслаждаемся.**
![image](https://user-images.githubusercontent.com/72695998/154973477-c877aac0-0f09-4744-9874-030e31639aef.png)
