### ISSUE TITLE
Join command not working

### ISSUE THREAD

**Issue by ManucrackYT** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#118]
Reason:  TypeError: Cannot read properties of undefined (reading 'selfDeaf')
    at Object.run (/home/container/commands/🎶 Music/join.js:47:35)
    at module.exports (/home/container/events/guild/messageCreate.js:309:17)
    at Client.emit (node:events:539:35)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)

**Comment by zalZEEY** [comment]
yes
