### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by progamer68** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#20]
I keep getting this error when I try running the bot:

```SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/discord-js-lavalink-Music-Bot-erela-js/node_modules/erela.js/dist/structures/Node.js:18:35)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
exit status 1```

**Comment by Tomato6966** [comment]
Start Lavalink First

**Comment by progamer68** [comment]
Can I DM you on discord? My user is progamer68#0833. I actually use a hosting service called repl.it

**Comment by Tomato6966** [comment]
It does not work on replit, as you can tell from the README.MD file you need to have 2 TERMINALS at the same time, cause u need to run LAVALINK.JAR

**Comment by fluffy29922** [comment]
which hosting do you recommend?

**Comment by Tomato6966** [comment]
https://bittmax.de --> JOin their Discord and use code `x10` to save 5% forever!

**Comment by arararat** [comment]
> It does not work on replit, as you can tell from the README.MD file you need to have 2 TERMINALS at the same time, cause u need to run LAVALINK.JAR

Bro you can host it on repl.it too host the lavalink on a repl and host bot on another but this is Too messy

**Comment by JacProsser** [comment]
or  you can just use a free lavalink server

**Comment by Tomato6966** [comment]
It is never suggested to use any free services for some complex things
The lavalink is a custom one too
So yea...

**Comment by JacProsser** [comment]
![Screenshot_75](https://user-images.githubusercontent.com/48368615/119741237-338cff80-be7d-11eb-8842-32cee0ca20df.png)
This is not bad at all.. and it is a free lavalink server for anyone to use

**Comment by Atharv-Pathak-14** [comment]
> It does not work on replit, as you can tell from the README.MD file you need to have 2 TERMINALS at the same time, cause u need to run LAVALINK.JAR

I think you should unpin this as you mentioned in repo that it's working now

**Comment by Fireball0201** [comment]
now it works on replit, please update it @Tomato6966

**Comment by Tomato6966** [comment]
Use the Current replit.com Clone: https://replit.com/@OxyTomato/Lava-Music?v=1
