### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by coco66688** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#62]
Error: Cannot find module 'node:events'
Require stack:
- /home/runner/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/index.js
- /home/runner/discord-js-lavalink-Music-Bot-erela-js/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/index.js',
    '/home/runner/discord-js-lavalink-Music-Bot-erela-js/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-js-lavalink-music-bot-erela-js-lava-music@8.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-js-lavalink-music-bot-erela-js-lava-music@8.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-04T07_47_14_740Z-debug.log
exit status 1

**Comment by AbdulReja** [comment]
[Install node.js 16](https://nodejs.org/dist/v16.13.1/node-v16.13.1-x64.msi)

For repl.it you can paste this code to your repl.it shell.
`npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH`

**Comment by Tomato6966** [comment]
Thanks for solving this Problem, AbdulReja, but i would suggest checking out our Replit Version too!
Which is 100% working fork ready! https://replit.com/@OxyTomato/Lava-Music?v=1
