### ISSUE TITLE
Error cannot find module 'node:events'

### ISSUE THREAD

**Issue by kdrlegend** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#65]
Hello i am receiving this error how do i fix it?

 
> Error: Cannot find module 'node:events' Require stack:

/home/container/node_modules/discord.js/src/client/BaseClient.js

/home/container/node_modules/discord.js/src/index.js

/home/container/index.js

at Function Module PesolveFilename (internal/modurles/es/Londer. 151880-15)

at Function. Module, load (internal/nodules/cjs/leader.js-725-27) at Module require (internal/modules/cs/loader-151952 19)

at require (internal/modules/cja/helpers. s:88, 10) at Object. <anonymous (/home/container/node_modules/discord.js/src/client/BaseClient.js:3:22) at Module. compale (internal/modules/cs/loader, js:106330)

at object Module extensions 1s (Internal/modules/ojs/loader.js:1002:16)

et Module-load (internal/modules/cs/loader js-928-32)

at Function. Nodule: Ioad (internal/modules/cja/londer, js:769-14)

OT Monale require internal/modules/39/loader.js:952:19) { code: "MODULE NOT FOUND',

requireStack: [

'/home/container/node_modules/discord.is/src/client/BaseClient.js', /home/container/node_modules/discord.js/src/index.js',
/home/container/index.js'

**Comment by testbot-github** [comment]
@kdrlegend Did u install node v16?
