### ISSUE TITLE
join command not working

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#70]
Hi, when i use the ?join command then the console says this: 

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read property 'selfDefean' of undefined
    at Object.run (/home/runner/soundpro/commands/🎶 Music/join.js:47:35)
    at module.exports (/home/runner/soundpro/events/guild/messageCreate.js:309:17)
    at Client.emit (node:events:406:35)
    at MessageCreateAction.handle (/home/runner/soundpro/node_modules/discord.js/src/client/actions/MessageCreate.js:25:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/soundpro/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/soundpro/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (/home/runner/soundpro/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/runner/soundpro/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/runner/soundpro/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:394:28)
=== UNHANDLED REJECTION ===

i already tryed to fix it but its still not working
@Tomato6966 pls help

**Comment by PatalJunior** [comment]
### I found the fix, you need to add this to your config file.

```json
"settings": {
    "selfDeaf": true
  },
```

### So it would look like this

```json
{
   "token": "Bot Token",
   "prefix": "?",
   "ownerIDS": [
      "442355791412854784"
   ],
   
   "status": {
      "text": "{prefix}help | played {songsplayed} Songs on {guildcount} Guilds | Support: discord.gg/milrato",
      "text2": "By: milrato.dev",
      "type": "PLAYING",
      "url": "https://twitch.tv/#"
   },
  "clientsettings": {
    "nodes": [
      {
        "host": "localhost",
        "port": 2333,
        "password": "youshallnotpass"
      }
    ]
  },

  "settings": {
    "selfDeaf": true
  },

   "spotify": {
      "clientID": "",
      "clientSecret": ""
   }
}

```

### The **true** or **false** being if the bot is deafen or not
@JanjyTapYT

**Comment by PatalJunior** [comment]
### I found the fix, you need to add this to your config file.

```json
"settings": {
    "selfDeaf": true
  },
```

### So it would look like this

```json
{
   "token": "Bot Token",
   "prefix": "?",
   "ownerIDS": [
      "442355791412854784"
   ],
   
   "status": {
      "text": "{prefix}help | played {songsplayed} Songs on {guildcount} Guilds | Support: discord.gg/milrato",
      "text2": "By: milrato.dev",
      "type": "PLAYING",
      "url": "https://twitch.tv/#"
   },
  "clientsettings": {
    "nodes": [
      {
        "host": "localhost",
        "port": 2333,
        "password": "youshallnotpass"
      }
    ]
  },

  "settings": {
    "selfDeaf": true
  },

   "spotify": {
      "clientID": "",
      "clientSecret": ""
   }
}

```

### The **true** or **false** being if the bot is deafen or not
@JanjyTapYT

**Comment by builtbyjonas** [comment]
Thank you

**Comment by PatalJunior** [comment]
> 

#72 This fixes it
