### ISSUE TITLE
Cannot read property 'updateVoiceState' of undefined

### ISSUE THREAD

**Issue by SteveModz** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#80]
Fresh fork of the bot and this is thrown, asked in the server and Jedd states that the client.manager exists

=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read property 'updateVoiceState' of undefined
    at module.exports (/home/runner/Lava-Music/events/client/raw.js:3:18)
    at Client.emit (node:events:394:28)
    at WebSocketShard.onMessage (/home/runner/Lava-Music/node_modules/discord.js/src/client/websocket/WebSocketShard.js:299:25)
    at WebSocket.onMessage (/home/runner/Lava-Music/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/Lava-Music/node_modules/discord.js/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/Lava-Music/node_modules/discord.js/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/runner/Lava-Music/node_modules/discord.js/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/runner/Lava-Music/node_modules/discord.js/node_modules/ws/lib/receiver.js:148:22)
=== UNCAUGHT EXCEPTION ===

raw.js code
module.exports = (client, d) => {
  client.manager.updateVoiceState(d)
}

**Comment by jerry-619** [comment]
Getting same error

**Comment by Hero2391** [comment]
Same error

**Comment by Tomato6966** [comment]
changing the code should fix this:
```js
//send raw audio data to the lavalink node
module.exports = (client, d) => {
  client.manager?.updateVoiceState(d);
}
```

it should only happen when the bot tries to send voice socket while the manager is not ready yet

**Comment by Hero2391** [comment]
And where i write that thing? In console or shell? Thanks.

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 10, 2022 at 20:40, ***@***.***> wrote:   


changing the code should fix this:
//send raw audio data to the lavalink node
module.exports = (client, d) => {
  client.manager?.updateVoiceState(d);
}
it should only happen when the bot tries to send voice socket while the manager is not ready yet

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JanjyTapYT** [comment]
> 

in events - client - raw.js
