### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by Hero2391** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#81]
=== UNHANDLED REJECTION ===
Reason:  RangeError: No available nodes.
    at new Player (/home/runner/SoundWave-REAL/node_modules/erela.js/dist/structures/Player.js:82:19)
    at Manager.create (/home/runner/SoundWave-REAL/node_modules/erela.js/dist/structures/Manager.js:205:16)
    at song (/home/runner/SoundWave-REAL/handlers/playermanagers/song.js:24:35)
    at module.exports (/home/runner/SoundWave-REAL/handlers/playermanager.js:64:37)
    at Object.run (/home/runner/SoundWave-REAL/commands/:notes: Music/play.js:63:7)
    at module.exports (/home/runner/SoundWave-REAL/events/guild/messageCreate.js:309:17)
    at Client.emit (node:events:406:35)
    at MessageCreateAction.handle (/home/runner/SoundWave-REAL/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/SoundWave-REAL/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/SoundWave-REAL/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
=== UNHANDLED REJECTION === 
I use this lavalink
 "host": "node01.lavalink.eu",
            "port": 2333,
            "password": "Raccoon"

Please help me

**Comment by jerry-619** [comment]
same errorr

**Comment by Tomato6966** [comment]
use a different lavalink node host
forexample node04.lavalink.eu
