### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#82]
Getting this error: 
TypeError: Cannot read properties of undefined (reading 'get')
    at change_status (/home/container/events/client/ready.js:48:47)
    at module.exports (/home/container/events/client/ready.js:24:5)
    at Client.emit (node:events:402:35)
    at WebSocketManager.triggerClientReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:367:10)
    at WebSocketShard.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:390:28)
    at WebSocketShard.checkReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    when i try to start the bot
    pls help

**Comment by Tomato6966** [comment]
dont use different repositories for npm module "enmap", use the original by typing `npm install enmap`
