### ISSUE TITLE
radio cmnd not working

### ISSUE THREAD

**Issue by jerry-619** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#83]
TypeError: Cannot read properties of undefined (reading 'length')
    at stations (C:\Users\Fardeen\Downloads\moozik-2\handlers\functions.js:232:38)
    at Object.run (C:\Users\Fardeen\Downloads\moozik-2\commands\🎶 Music\radio.js:25:26)
    at module.exports (C:\Users\Fardeen\Downloads\moozik-2\events\guild\messageCreate.js:309:17)
    at Client.emit (node:events:406:35)
    at MessageCreateAction.handle (C:\Users\Fardeen\Downloads\moozik-2\node_modules\discord.js\src\client\actions\MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Fardeen\Downloads\moozik-2\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Fardeen\Downloads\moozik-2\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (C:\Users\Fardeen\Downloads\moozik-2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Fardeen\Downloads\moozik-2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Fardeen\Downloads\moozik-2\node_modules\ws\lib\event-target.js:199:18)

**Comment by Tomato6966** [comment]
hmmmm

**Comment by ManucrackYT** [comment]
I've got the same error
