### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by coco66688** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#92]
Exception:  TypeError: Cannot read properties of undefined (reading 'updateVoiceState')
    at module.exports (/home/runner/Lava-Music-1/events/client/raw.js:3:18)
    at Client.emit (node:events:390:28)
    at WebSocketShard.onMessage (/home/runner/Lava-Music-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:299:25)
    at WebSocket.onMessage (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/receiver.js:148:22)

**Comment by Akshit1025** [comment]
> Exception: TypeError: Cannot read properties of undefined (reading 'updateVoiceState') at module.exports (/home/runner/Lava-Music-1/events/client/raw.js:3:18) at Client.emit (node:events:390:28) at WebSocketShard.onMessage (/home/runner/Lava-Music-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:299:25) at WebSocket.onMessage (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18) at WebSocket.emit (node:events:390:28) at Receiver.receiverOnMessage (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/websocket.js:1098:20) at Receiver.emit (node:events:390:28) at Receiver.dataMessage (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/receiver.js:528:14) at Receiver.getData (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/receiver.js:446:17) at Receiver.startLoop (/home/runner/Lava-Music-1/node_modules/discord.js/node_modules/ws/lib/receiver.js:148:22)

are you hosting on replit.com ??

**Comment by coco66688** [comment]
> 
yes

**Comment by Tomato6966** [comment]
it's not fully supported on replit.com

**Comment by Tomato6966** [comment]
make sure to use my fork
