### ISSUE TITLE
The bot is not coming online ;-;

### ISSUE THREAD

**Issue by wanheda-123** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#98]
Whenever I run the code the terminal shows this error and i don't know what this error means. Also i am hosting my bot on repl.it with hacker plan.
`=== UNHANDLED REJECTION ===
Reason:  Error: Request failed with status code 400
    at createError (/home/runner/Lava-Music/node_modules/erela.js-spotify/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/Lava-Music/node_modules/erela.js-spotify/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/runner/Lava-Music/node_modules/erela.js-spotify/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
=== UNHANDLED REJECTION ===`

**Comment by mcdaddytalk** [comment]
@wanheda-123 If you disable the spotify plugin does it error?   I had issues with `erela.js-spotify` and moved to `better-erela.js-spotify` and also had to regen my spotify api key.  Give it a shot.

**Comment by Almazmsi** [comment]
> Whenever I run the code the terminal shows this error and i don't know what this error means. Also i am hosting my bot on repl.it with hacker plan. `=== UNHANDLED REJECTION === Reason: Error: Request failed with status code 400 at createError (/home/runner/Lava-Music/node_modules/erela.js-spotify/node_modules/axios/lib/core/createError.js:16:15) at settle (/home/runner/Lava-Music/node_modules/erela.js-spotify/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/home/runner/Lava-Music/node_modules/erela.js-spotify/node_modules/axios/lib/adapters/http.js:244:11) at IncomingMessage.emit (node:events:406:35) at endReadableNT (node:internal/streams/readable:1331:12) at processTicksAndRejections (node:internal/process/task_queues:83:21) === UNHANDLED REJECTION ===`

Man check https://ptb.discord.com/channels/773668217163218944/898249595950350337/944594207958507521
modules
