### ISSUE TITLE
errors on command

### ISSUE THREAD

**Issue by MondoPIX** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#99]
queue command
```
=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setAuthor (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/structures/MessageEmbed.js:392:32)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queue.js:45:12)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===

```

**Comment by MondoPIX** [comment]
radio command

```
TypeError: Cannot read properties of undefined (reading 'length')
    at stations (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/handlers/functions.js:232:38)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/radio.js:25:26)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)

```

**Comment by MondoPIX** [comment]
queuestatus
```

=== UNHANDLED REJECTION ===
Reason:  ReferenceError: createBar is not defined
    at eval (eval at run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queuestatus.js:38:90), <anonymous>:1:40)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/queuestatus.js:38:90)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===

```

**Comment by MondoPIX** [comment]
np command

```
=== UNHANDLED REJECTION ===
Reason:  RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string.
    at Function.verifyString (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setAuthor (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/node_modules/discord.js/src/structures/MessageEmbed.js:392:32)
    at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/nowplaying.js:31:8)
    at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
=== UNHANDLED REJECTION ===
```

**Comment by TechnoHaX** [comment]
Same errors given on the language command too. I think it's either a discord or a node bug. (I can't paste the error codes currently but it's not necessary because it's almost the same.)

**Comment by Almazmsi** [comment]
queue bug i fix xD

i see error 
![WindowsTerminal_U7QUhofdy3](https://user-images.githubusercontent.com/72695998/154823740-6f1bd815-4231-43c2-ab39-300054574109.png)

fix 
![Code_-_Insiders_U6wr2njs7s](https://user-images.githubusercontent.com/72695998/154823752-bf62776f-bd92-4ace-a837-577640d29eca.png)
![Code_-_Insiders_dIy2vSZMMa](https://user-images.githubusercontent.com/72695998/154823756-cee81dde-f73f-4209-86f7-4d1bff1f80af.png)

Done
![DiscordPTB_ILmZeMJdat](https://user-images.githubusercontent.com/72695998/154823819-240634c5-0688-443b-81b8-efd3d28b2e2b.png)

**Comment by Almazmsi** [comment]
> radio command
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'length')
>     at stations (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/handlers/functions.js:232:38)
>     at Object.run (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/commands/🎶 Music/radio.js:25:26)
>     at module.exports (/home/botdiscord/discord-js-lavalink-Music-Bot-erela-js/events/guild/messageCreate.js:309:17)
> ```

I`m not fixed xD

**Comment by Almazmsi** [comment]
@MondoPIX give me 20 min, i fixed np and statusbar)

**Comment by Almazmsi** [comment]
@MondoPIX 
Fixed NP

Error
![WindowsTerminal_F08LafnlZV](https://user-images.githubusercontent.com/72695998/154823917-40bd3fa8-370d-446f-b764-564f26edd051.png)

Fix
![Code_-_Insiders_bl90NI1bWF](https://user-images.githubusercontent.com/72695998/154823929-67a0568d-4446-4907-9e85-d9a97409e519.png)

Done
![DiscordPTB_ZTEhBrEJd5](https://user-images.githubusercontent.com/72695998/154823936-37049b61-3253-4f57-82a0-6ccbe1c010b5.png)

**Comment by Almazmsi** [comment]
@MondoPIX Fix queuestatus

Error
![WindowsTerminal_J16fVAW0D4](https://user-images.githubusercontent.com/72695998/154823996-c0885cc4-192f-465b-8070-79a8f2f66a63.png)

Fix
![Code_-_Insiders_m8wc8IXVDT](https://user-images.githubusercontent.com/72695998/154824005-3095162d-0b7e-474d-b89e-7e5e0fdfbee7.png)

Done
![DiscordPTB_YmBJYpzsXx](https://user-images.githubusercontent.com/72695998/154824007-ee141856-d0ef-41b3-9747-14e0892ac28a.png)

**Comment by TechnoHaX** [comment]
@Almazmsi
Thank you very much <3
May you check the other commands too when you have the time for it, please?

**Comment by Almazmsi** [comment]
@TechnoHaX 
I will finish the post first and go on to check the commands. If I find something wrong, I will add in my post how to fix it.
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/issues/100

**Comment by Almazmsi** [comment]
@TechnoHaX check post. Fix error Language)
